name: Validate Terraform Configuration
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
      - name: Terraform Init
        run: terraform init
      - name: Terraform Fmt
        run: terraform fmt
      - name: Terraform Validate
        run: terraform validate